//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.AsmxService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Phone : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_nameField;
        
        private int Phone_numberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Last_name {
            get {
                return this.Last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_nameField, value) != true)) {
                    this.Last_nameField = value;
                    this.RaisePropertyChanged("Last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Phone_number {
            get {
                return this.Phone_numberField;
            }
            set {
                if ((this.Phone_numberField.Equals(value) != true)) {
                    this.Phone_numberField = value;
                    this.RaisePropertyChanged("Phone_number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsmxService.PhoneServiceSoap")]
    public interface PhoneServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetPhonesResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhones", ReplyAction="*")]
        Client.AsmxService.GetPhonesResponse GetPhones(Client.AsmxService.GetPhonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhones", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.AsmxService.GetPhonesResponse> GetPhonesAsync(Client.AsmxService.GetPhonesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPhone", ReplyAction="*")]
        Client.AsmxService.AddPhoneResponse AddPhone(Client.AsmxService.AddPhoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPhone", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.AsmxService.AddPhoneResponse> AddPhoneAsync(Client.AsmxService.AddPhoneRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdPhone", ReplyAction="*")]
        Client.AsmxService.UpdPhoneResponse UpdPhone(Client.AsmxService.UpdPhoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdPhone", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.AsmxService.UpdPhoneResponse> UpdPhoneAsync(Client.AsmxService.UpdPhoneRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем phone из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelPhone", ReplyAction="*")]
        Client.AsmxService.DelPhoneResponse DelPhone(Client.AsmxService.DelPhoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelPhone", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.AsmxService.DelPhoneResponse> DelPhoneAsync(Client.AsmxService.DelPhoneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhonesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhones", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.GetPhonesRequestBody Body;
        
        public GetPhonesRequest() {
        }
        
        public GetPhonesRequest(Client.AsmxService.GetPhonesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPhonesRequestBody {
        
        public GetPhonesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPhonesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPhonesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.GetPhonesResponseBody Body;
        
        public GetPhonesResponse() {
        }
        
        public GetPhonesResponse(Client.AsmxService.GetPhonesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPhonesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.AsmxService.Phone[] GetPhonesResult;
        
        public GetPhonesResponseBody() {
        }
        
        public GetPhonesResponseBody(Client.AsmxService.Phone[] GetPhonesResult) {
            this.GetPhonesResult = GetPhonesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPhone", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.AddPhoneRequestBody Body;
        
        public AddPhoneRequest() {
        }
        
        public AddPhoneRequest(Client.AsmxService.AddPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.AsmxService.Phone phone;
        
        public AddPhoneRequestBody() {
        }
        
        public AddPhoneRequestBody(Client.AsmxService.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.AddPhoneResponseBody Body;
        
        public AddPhoneResponse() {
        }
        
        public AddPhoneResponse(Client.AsmxService.AddPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddPhoneResponseBody {
        
        public AddPhoneResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdPhone", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.UpdPhoneRequestBody Body;
        
        public UpdPhoneRequest() {
        }
        
        public UpdPhoneRequest(Client.AsmxService.UpdPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdPhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.AsmxService.Phone phone;
        
        public UpdPhoneRequestBody() {
        }
        
        public UpdPhoneRequestBody(Client.AsmxService.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.UpdPhoneResponseBody Body;
        
        public UpdPhoneResponse() {
        }
        
        public UpdPhoneResponse(Client.AsmxService.UpdPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdPhoneResponseBody {
        
        public UpdPhoneResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelPhone", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.DelPhoneRequestBody Body;
        
        public DelPhoneRequest() {
        }
        
        public DelPhoneRequest(Client.AsmxService.DelPhoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelPhoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.AsmxService.Phone phone;
        
        public DelPhoneRequestBody() {
        }
        
        public DelPhoneRequestBody(Client.AsmxService.Phone phone) {
            this.phone = phone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelPhoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.AsmxService.DelPhoneResponseBody Body;
        
        public DelPhoneResponse() {
        }
        
        public DelPhoneResponse(Client.AsmxService.DelPhoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelPhoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DelPhoneResult;
        
        public DelPhoneResponseBody() {
        }
        
        public DelPhoneResponseBody(bool DelPhoneResult) {
            this.DelPhoneResult = DelPhoneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PhoneServiceSoapChannel : Client.AsmxService.PhoneServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneServiceSoapClient : System.ServiceModel.ClientBase<Client.AsmxService.PhoneServiceSoap>, Client.AsmxService.PhoneServiceSoap {
        
        public PhoneServiceSoapClient() {
        }
        
        public PhoneServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.AsmxService.GetPhonesResponse Client.AsmxService.PhoneServiceSoap.GetPhones(Client.AsmxService.GetPhonesRequest request) {
            return base.Channel.GetPhones(request);
        }
        
        public Client.AsmxService.Phone[] GetPhones() {
            Client.AsmxService.GetPhonesRequest inValue = new Client.AsmxService.GetPhonesRequest();
            inValue.Body = new Client.AsmxService.GetPhonesRequestBody();
            Client.AsmxService.GetPhonesResponse retVal = ((Client.AsmxService.PhoneServiceSoap)(this)).GetPhones(inValue);
            return retVal.Body.GetPhonesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.AsmxService.GetPhonesResponse> Client.AsmxService.PhoneServiceSoap.GetPhonesAsync(Client.AsmxService.GetPhonesRequest request) {
            return base.Channel.GetPhonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.AsmxService.GetPhonesResponse> GetPhonesAsync() {
            Client.AsmxService.GetPhonesRequest inValue = new Client.AsmxService.GetPhonesRequest();
            inValue.Body = new Client.AsmxService.GetPhonesRequestBody();
            return ((Client.AsmxService.PhoneServiceSoap)(this)).GetPhonesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.AsmxService.AddPhoneResponse Client.AsmxService.PhoneServiceSoap.AddPhone(Client.AsmxService.AddPhoneRequest request) {
            return base.Channel.AddPhone(request);
        }
        
        public void AddPhone(Client.AsmxService.Phone phone) {
            Client.AsmxService.AddPhoneRequest inValue = new Client.AsmxService.AddPhoneRequest();
            inValue.Body = new Client.AsmxService.AddPhoneRequestBody();
            inValue.Body.phone = phone;
            Client.AsmxService.AddPhoneResponse retVal = ((Client.AsmxService.PhoneServiceSoap)(this)).AddPhone(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.AsmxService.AddPhoneResponse> Client.AsmxService.PhoneServiceSoap.AddPhoneAsync(Client.AsmxService.AddPhoneRequest request) {
            return base.Channel.AddPhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.AsmxService.AddPhoneResponse> AddPhoneAsync(Client.AsmxService.Phone phone) {
            Client.AsmxService.AddPhoneRequest inValue = new Client.AsmxService.AddPhoneRequest();
            inValue.Body = new Client.AsmxService.AddPhoneRequestBody();
            inValue.Body.phone = phone;
            return ((Client.AsmxService.PhoneServiceSoap)(this)).AddPhoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.AsmxService.UpdPhoneResponse Client.AsmxService.PhoneServiceSoap.UpdPhone(Client.AsmxService.UpdPhoneRequest request) {
            return base.Channel.UpdPhone(request);
        }
        
        public void UpdPhone(Client.AsmxService.Phone phone) {
            Client.AsmxService.UpdPhoneRequest inValue = new Client.AsmxService.UpdPhoneRequest();
            inValue.Body = new Client.AsmxService.UpdPhoneRequestBody();
            inValue.Body.phone = phone;
            Client.AsmxService.UpdPhoneResponse retVal = ((Client.AsmxService.PhoneServiceSoap)(this)).UpdPhone(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.AsmxService.UpdPhoneResponse> Client.AsmxService.PhoneServiceSoap.UpdPhoneAsync(Client.AsmxService.UpdPhoneRequest request) {
            return base.Channel.UpdPhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.AsmxService.UpdPhoneResponse> UpdPhoneAsync(Client.AsmxService.Phone phone) {
            Client.AsmxService.UpdPhoneRequest inValue = new Client.AsmxService.UpdPhoneRequest();
            inValue.Body = new Client.AsmxService.UpdPhoneRequestBody();
            inValue.Body.phone = phone;
            return ((Client.AsmxService.PhoneServiceSoap)(this)).UpdPhoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.AsmxService.DelPhoneResponse Client.AsmxService.PhoneServiceSoap.DelPhone(Client.AsmxService.DelPhoneRequest request) {
            return base.Channel.DelPhone(request);
        }
        
        public bool DelPhone(Client.AsmxService.Phone phone) {
            Client.AsmxService.DelPhoneRequest inValue = new Client.AsmxService.DelPhoneRequest();
            inValue.Body = new Client.AsmxService.DelPhoneRequestBody();
            inValue.Body.phone = phone;
            Client.AsmxService.DelPhoneResponse retVal = ((Client.AsmxService.PhoneServiceSoap)(this)).DelPhone(inValue);
            return retVal.Body.DelPhoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.AsmxService.DelPhoneResponse> Client.AsmxService.PhoneServiceSoap.DelPhoneAsync(Client.AsmxService.DelPhoneRequest request) {
            return base.Channel.DelPhoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.AsmxService.DelPhoneResponse> DelPhoneAsync(Client.AsmxService.Phone phone) {
            Client.AsmxService.DelPhoneRequest inValue = new Client.AsmxService.DelPhoneRequest();
            inValue.Body = new Client.AsmxService.DelPhoneRequestBody();
            inValue.Body.phone = phone;
            return ((Client.AsmxService.PhoneServiceSoap)(this)).DelPhoneAsync(inValue);
        }
    }
}
